[project]
name = "gift-finder"
version = "0.1.0"
description = ""
authors = [
    {name = "Anton Danilyuk",email = "danilyuk.anton2023@mail.ru"}
]
requires-python = ">=3.12,<4"
dependencies = [
    "django (==6.0.3)",
    "psycopg2-binary (==2.9.11)",
    "django-environ (==0.13.0)",
    "djangorestframework (==3.17.1)",
    "django-filter (==25.2)",
    "drf-spectacular (==0.29.0)",
    "pillow (==12.2.0)",
    "django-debug-toolbar (==6.3.0)",
    "djangorestframework-stubs (==3.16.9)",
    "djangorestframework-simplejwt (==5.5.1)",
    "django-redis (==6.0.0)",
    "pyjwt (>=2.13.0,<3.0.0)",
    "django-oauth-toolkit (>=3.4.0,<4.0.0)",
    "social-auth-app-django (>=6.0.1,<7.0.0)",
    "drf-social-oauth2 (>=3.4.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.1,<0.17.0)",
    "pre-commit (>=4.6.1,<5.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.ruff]
exclude = [
    "*/migrations/*.py",
    "src/custom_router.py",
]

[tool.ruff.lint.per-file-ignores]
"src/config/settings/*.py" = ["F403", "F405"]

[tool.poetry]
package-mode = false