# Generated by Django 6.0.3 on 2026-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_chosenproducts_created_at_chosenproducts_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosenproducts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chosenproducts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
