# Generated by Django 6.0.3 on 2026-04-28 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_chosenproducts_created_at_and_more"),
        ("gifts", "0009_alter_direction_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChosenProducts",
            new_name="Cart",
        ),
    ]
