# Generated by Django 6.0.3 on 2026-04-28 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_chosenproducts_cart"),
        ("gifts", "0009_alter_direction_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
            },
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="options",
            field=models.ManyToManyField(
                blank=True, related_name="search_histories", to="gifts.option"
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
