# Generated by Django 6.0.3 on 2026-04-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_searchhistory_options_and_more"),
        ("gifts", "0009_alter_direction_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedsearch",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
            },
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name of selection"),
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="options",
            field=models.ManyToManyField(
                related_name="saved_searches", to="gifts.option", verbose_name="Options"
            ),
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_searches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterModelTable(
            name="savedsearch",
            table="accounts_saved_search",
        ),
    ]
