# Generated by Django 6.0.3 on 2026-04-28 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_savedsearch_options_alter_savedsearch_name_and_more"),
        ("gifts", "0009_alter_direction_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.RemoveField(
            model_name="cart",
            name="selected_at",
        ),
        migrations.AlterField(
            model_name="cart",
            name="is_purchased",
            field=models.BooleanField(default=False, verbose_name="Is purchased"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="gifts.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "is_purchased"),
                name="unique_user_product_active",
            ),
        ),
    ]
