# Generated by Django 6.0.3 on 2026-03-10 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500, verbose_name="Question")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("multiple", "Multiple"),
                            ("text", "Text"),
                        ],
                        default="multiple",
                        max_length=10,
                        verbose_name="Question Type",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="requires image link",
                        max_length=255,
                        null=True,
                        verbose_name="Image URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "Questions",
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of direction"),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="requires image link",
                        max_length=255,
                        null=True,
                        verbose_name="Image URL",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="gifts.direction",
                        verbose_name="Parent ID",
                    ),
                ),
                ("tags", models.ManyToManyField(to="gifts.tag", verbose_name="Tags")),
            ],
            options={
                "verbose_name": "Direction",
                "verbose_name_plural": "Directions",
                "db_table": "Directions",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of product"),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BYN", "Byn"),
                            ("RUB", "Rub"),
                            ("USD", "Usd"),
                            ("EUR", "Eur"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="requires image link",
                        max_length=255,
                        null=True,
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "additional_image_url",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="requires image link",
                        null=True,
                        verbose_name="Additional Image URL",
                    ),
                ),
                (
                    "product_url",
                    models.URLField(
                        blank=True,
                        help_text="requires image link",
                        max_length=255,
                        null=True,
                        verbose_name="Product URL",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="requires shop name",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("reviews_count", models.IntegerField(verbose_name="Reviews Count")),
                (
                    "in_stock",
                    models.BooleanField(default=False, verbose_name="In stock"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(auto_now=True, verbose_name="Last Checked"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="gifts.direction",
                        verbose_name="Directions",
                    ),
                ),
                ("tags", models.ManyToManyField(to="gifts.tag", verbose_name="Tags")),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=200, verbose_name="Answer")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="requires image link",
                        max_length=255,
                        null=True,
                        verbose_name="Image URL",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="gifts.question",
                        verbose_name="Question",
                    ),
                ),
                ("tags", models.ManyToManyField(to="gifts.tag", verbose_name="Tags")),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "db_table": "Options",
                "ordering": ["question__order", "order"],
            },
        ),
    ]
