# Generated by Django 6.0.3 on 2026-03-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0002_producttag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="gifts.question",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Tag name"),
        ),
        migrations.DeleteModel(
            name="ProductTag",
        ),
    ]
