# Generated by Django 6.0.3 on 2026-03-27 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Priority'),
        ),
    ]
