# Generated by Django 6.0.3 on 2026-04-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0005_question_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="priority",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Priority",
            ),
        ),
    ]
