# Generated by Django 6.0.3 on 2026-05-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0009_alter_direction_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_required",
            field=models.BooleanField(default=True, verbose_name="Required"),
        ),
    ]
