# Generated by Django 6.0.3 on 2026-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0010_question_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("required", "Required"), ("additional", "Additional")],
                default="required",
                max_length=10,
                verbose_name="Question Status",
            ),
        ),
    ]
