# Generated by Django 6.0.3 on 2026-05-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0011_question_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_required",
        ),
    ]
